// WebSite with CosmosDB/client/nba-statistics/src/pages/Statistics.tsx
import React, { useEffect, useState } from 'react';
import { Box, InputLabel, MenuItem, FormControl, Select, Button, Divider, IconButton, Typography, useMediaQuery } from '@mui/material';
import { format } from 'date-fns';
import { SelectChangeEvent } from '@mui/material/Select';
import { useDispatch, useSelector } from 'react-redux';
import { RootState, AppDispatch } from '../stores/Store';
import { fetchSeasons, fetchGames, fetchPlayers } from '../stores/Selection';
import globalTheme from '../styles/GlobalTheme';
import { fetchStatistics, resetStatistics } from '../stores/Statistics';
import StatBox from '../components/StatsBox';
import QueryStatsIcon from '@mui/icons-material/QueryStats';
import RefreshIcon from '@mui/icons-material/Refresh';
import { Season } from '../models/Selection/Season';
import { Game } from '../models/Selection/Game';
import { Participation } from '../models/Selection/Participation';

const Statistics: React.FC = () => {
  const dispatch: AppDispatch = useDispatch();

  const { seasons, games, players, statistics, error } = useSelector(
    (state: RootState) => ({
      seasons: state.seasons.seasons,
      games: state.games.games,
      players: state.players.players,
      statistics: state.statistics,
      error: state.statistics.error || state.seasons.error || state.games.error || state.players.error
    })
  );

  const [selectedSeason, setSelectedSeason] = useState<Season | null>(null);
  const [selectedGame, setSelectedGame] = useState<Game | null>(null);
  const [selectedPlayer, setSelectedPlayer] = useState<Participation | null>(null);
  const [timeElapsed, setTimeElapsed] = useState<number | null>(null);

  useEffect(() => {
    dispatch(fetchSeasons());
  }, [dispatch]);

  useEffect(() => {
    dispatch(resetStatistics());
    setSelectedSeason(null);
    setSelectedGame(null);
    setSelectedPlayer(null);
    setTimeElapsed(null);
  }, [dispatch]);

  useEffect(() => {
    if (selectedSeason) {
      dispatch(fetchGames(selectedSeason.id));
    }
  }, [dispatch, selectedSeason]);

  useEffect(() => {
    if (selectedGame) {
      dispatch(fetchPlayers(selectedGame.id));
    }
  }, [dispatch, selectedGame]);

  useEffect(() => {
    if (statistics.lastUpdated) {
      const lastUpdated = statistics.lastUpdated || null
      const intervalId = setInterval(() => {
        const secondsElapsed = Math.floor((Date.now() - new Date(lastUpdated).getTime()) / 1000);
        setTimeElapsed(secondsElapsed);
      }, 1000);

      return () => clearInterval(intervalId);
    }
  }, [statistics.lastUpdated]);

  useEffect(() => {
    if (timeElapsed === null || timeElapsed >= 60) {
      handleStats();
    }
  }, [timeElapsed]);

  const handleSeasonChange = (event: SelectChangeEvent<string>) => {
    const selectedSeasonId = event.target.value;
    const selectedSeason = seasons.find((s) => s.id === selectedSeasonId);
    setSelectedSeason(selectedSeason || null);
    setSelectedGame(null);
    setSelectedPlayer(null);
  };

  const handleGameChange = (event: SelectChangeEvent<string>) => {
    const selectedGameId = event.target.value;
    const selectedGame = games.find((game) => game.id === selectedGameId);
    setSelectedGame(selectedGame || null);
    setSelectedPlayer(null);
  };

  const handlePlayerChange = (event: SelectChangeEvent<string>) => {
    const selectedPlayerId = event.target.value;
    const selectedPlayer = players.find((player) => player.id === selectedPlayerId);
    setSelectedPlayer(selectedPlayer || null);
  };

  const handleStats = () => {
    if (selectedSeason && selectedGame && selectedPlayer) {
      dispatch(fetchStatistics(selectedSeason.id, selectedGame.id, selectedPlayer.id));
    }
  };

  const isMobile = useMediaQuery('(max-width: 450px)');

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: isMobile ? 'column' : 'row',
        alignItems: 'flex-start',
        gap: 2,
        position: 'absolute',
        top: '50%',
        left: isMobile ? '2%' : '5%',
        transform: 'translateY(-50%)',
        width: isMobile ? '96%' : '90%',
        paddingTop: isMobile ? '80px' : '120px',
        paddingBottom: isMobile ? '50px' : '120px',
        overflowY: 'auto',
        maxHeight: '100vh',
      }}
    >
      <Box
        sx={{
          width: isMobile ? '100%' : '20%',
          display: 'flex',
          flexDirection: 'column',
          gap: 2,
          marginTop: isMobile ? 12 : 0,
          paddingRight: isMobile ? 2 : 0,
          paddingLeft: isMobile ? 2 : 0
        }}
      >
        <Typography gutterBottom sx={{ ...globalTheme.typography.h2 }}>Pick a player</Typography>
        {error ? (
          <Typography gutterBottom sx={{ ...globalTheme.typography.h2 }}>{error}</Typography>) : ('')
        }
        <FormControl fullWidth>
          <InputLabel id="season-label" sx={{ color: globalTheme.palette.primary.main }}>Season</InputLabel>
          <Select
            labelId="season-label"
            id="season-select"
            value={selectedSeason?.id}
            label="Season"
            onChange={handleSeasonChange}
            disabled={statistics.loading}
          >
            {seasons.map((season) => (
              <MenuItem key={season.id} value={season.id}>
                {season.id}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
        <FormControl fullWidth>
          <InputLabel id="game-label" sx={{ color: globalTheme.palette.primary.main }}>Game</InputLabel>
          <Select
            labelId="game-label"
            id="game-select"
            value={selectedGame?.id || ''}
            label="Game"
            onChange={handleGameChange}
            disabled={!selectedSeason}
          >
            {games.map((game) => (
              <MenuItem key={game.id} value={game.id}>
                {game.homeTeamId} vs {game.visitorTeamId}, {format(game.at, 'MMM dd')}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
        <FormControl fullWidth>
          <InputLabel id="player-label" sx={{ color: globalTheme.palette.primary.main }}>Player</InputLabel>
          <Select
            labelId="player-label"
            id="player-select"
            value={selectedPlayer?.id || ''}
            label="Player"
            onChange={handlePlayerChange}
            disabled={!selectedGame}
          >
            {players.map((player) => (
              <MenuItem key={player.id} value={player.id}>
                {player.name}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
        <Button
          variant="contained"
          color="primary"
          startIcon={<QueryStatsIcon />}
          disabled={!!statistics.ofGame || (!selectedSeason || !selectedGame || !selectedPlayer)}
          sx={{
            width: '100%',
            fontSize: globalTheme.typography.h3,
            color: globalTheme.palette.background.default,
            height: 45,
            marginTop: 2,
            borderRadius: 4,
            backgroundColor: globalTheme.palette.primary.main,
            '&:hover': {
              backgroundColor: globalTheme.palette.primary.dark
            },
            '&.Mui-disabled': {
              color: 'black',
              backgroundColor: globalTheme.palette.grey[700],
            }
          }}
          onClick={handleStats}
        >
          FILTER
        </Button>
      </Box>
      <Divider
        orientation={isMobile ? 'vertical' : 'horizontal'}
        flexItem
        sx={{ marginLeft: isMobile ? 0 : 2, marginRight: isMobile ? 0 : 2, borderColor: globalTheme.palette.primary.main, borderWidth: 2, marginTop: isMobile ? 4 : 0 }}
      />
      <Box
        sx={{
          width: isMobile ? '100%' : '75%',
          height: '650',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'left',
          paddingLeft: isMobile ? 0 : 4,
          gap: 2,
          marginTop: isMobile ? 3 : 0,
        }}>
        {statistics.ofGame || statistics.ofSeason ? (
          <>
            <Box sx={{
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <Typography sx={{ fontSize: globalTheme.typography.h2 }} gutterBottom>
                Performance
              </Typography>
              <Box sx={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: 1
              }}>
                <IconButton aria-label="refresh" sx={{
                  color: globalTheme.palette.background.default, backgroundColor: globalTheme.palette.primary.main,
                  '&:hover': {
                    backgroundColor: globalTheme.palette.primary.dark
                  }
                }}
                  onClick={handleStats}
                >
                  <RefreshIcon />
                </IconButton>
                <Typography sx={{ fontSize: globalTheme.typography.h5 }}>Updated <br />{timeElapsed !== null ? `${timeElapsed}s ago` : "now"}
                </Typography>
              </Box>
            </Box>
            <Box
              sx={{
                width: 'auto',
                backgroundColor: 'rgba(0, 0, 0, 0.1)',
                padding: 2,
                display: 'grid',
                gridTemplateRows: '1fr auto',
                gap: 2,
              }}
            >
              <Typography
                variant={isMobile ? "h5" : "h2"}
                gutterBottom
                textAlign="center"
              >
                In the season ({statistics.ofSeason?.participations && statistics.ofSeason.participations > 0 ? `${statistics.ofSeason.participations} game${statistics.ofSeason.participations > 1 ? 's' : ''}` : '0 games'})
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
                  gap: 2,
                  marginTop: 2,
                  '@media (max-width: 400px)': {
                    gridTemplateColumns: '1fr',
                  },
                }}
              >
                <StatBox label="PPG" value={statistics.ofSeason?.ppg?.toFixed(1) || ''} />
                <StatBox label="APG" value={statistics.ofSeason?.apg?.toFixed(1) || ''} />
                <StatBox label="RPG" value={statistics.ofSeason?.rpg?.toFixed(1) || ''} />
                <StatBox label="BPG" value={statistics.ofSeason?.bpg?.toFixed(1) || ''} />
                <StatBox label="FT%" value={statistics.ofSeason?.ftConversion?.toFixed(1) || ''} />
                <StatBox label="Total Points" value={statistics.ofSeason?.totalPoints || ''} />
              </Box>
            </Box>
            <Box
              sx={{
                width: 'auto',
                backgroundColor: 'rgba(0, 0, 0, 0.1)',
                padding: 2,
                borderRadius: 1,
              }}
            >
              <Typography
                variant={isMobile ? 'h5' : 'h2'}
                gutterBottom
                textAlign="center"
                sx={{
                  marginBottom: isMobile ? 1 : 2, gridTemplateColumns: isMobile ? '1fr' : 'repeat(8, 1fr)',
                }}
              >
                In the game
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: isMobile ? '1fr' : 'repeat(8, 1fr)',
                  gap: 2,
                  marginTop: 2,
                }}
              >
                <StatBox label="FT" value={`${statistics.ofGame?.find(t => t.type === 'FreeThrowHit')?.count ?? 0}-${statistics.ofGame?.filter(t => t.type === 'FreeThrowMiss' || t.type === 'FreeThrowHit')?.reduce((sum, t) => sum + t.count, 0) ?? 0}`} />
                <StatBox label="2PT" value={`${statistics.ofGame?.find(t => t.type === 'TwoPointerHit')?.count ?? 0}-${statistics.ofGame?.filter(t => t.type === 'TwoPointerMiss' || t.type === 'TwoPointerHit')?.reduce((sum, t) => sum + t.count, 0) ?? 0}`} />
                <StatBox label="3PT" value={`${statistics.ofGame?.find(t => t.type === 'ThreePointerHit')?.count ?? 0}-${statistics.ofGame?.filter(t => t.type === 'ThreePointerMiss' || t.type === 'ThreePointerHit')?.reduce((sum, t) => sum + t.count, 0) ?? 0}`} />
                <StatBox label="Assist" value={statistics.ofGame?.find(t => t.type === "Assist")?.count ?? 0} />
                <StatBox label="Rebound" value={statistics.ofGame?.find(t => t.type === "Rebound")?.count ?? 0} />
                <StatBox label="Turnover" value={statistics.ofGame?.find(t => t.type === "Turnover")?.count ?? 0} />
                <StatBox label="Block" value={statistics.ofGame?.find(t => t.type === "Block")?.count ?? 0} />
                <StatBox label="Foul" value={statistics.ofGame?.find(t => t.type === "Foul")?.count ?? 0} />
                <StatBox
                  position="center"
                  label="Total Points"
                  sx={{
                    gridColumn: isMobile ? 'auto' : 'span 8',
                    boxWidth: isMobile ? "auto" : "500px"
                  }}
                  value={statistics.ofGame?.reduce((total, t) => t.points ? total + t.points : total, 0) ?? 0}
                />
              </Box>
            </Box>
          </>
        ) : (
          <Box
            sx={{
              height: isMobile ? '100' : '550px',
              borderRadius: 1,
              backgroundColor: 'rgba(0, 0, 0, 0.1)',
              justifyContent: 'center',
              alignItems: 'center',
              display: 'flex',
            }}
          >
            <Typography
              variant="h1"
              align="center"
              gutterBottom
              sx={{
                ...globalTheme.typography.h2
              }}
            >
              {isMobile ? 'Fill the filtering fields to the top' : 'Fill the filtering fields to the left'}
            </Typography>
          </Box>

        )}
      </Box>
    </Box >
  );
};

export default Statistics;

// Vue-Nuxt with Java-MongoDB/client/nba-statistics/pages/statistics/index.vue
<template>
  <v-container fluid class="main-container">
    <v-row justify="center" class="justify-sm-start">
      <v-col cols="10" sm="2" class="text-center pa-10">
        <h1 class="text-h4 mt-10">Details</h1>

        <v-select
          class="mt-10"
          label="Season"
          :items="selectionStore.seasons"
          item-title="id"
          item-value="id"
          v-model="selectedSeason"
          @update:modelValue="onSeasonSelect"
        ></v-select>

        <v-select
          class="mt-10"
          label="Game"
          :items="selectionStore.games"
          :item-title="gameTitle"
          item-value="id"
          v-model="selectedGame"
          @update:modelValue="onGameSelect"
        ></v-select>

        <v-select
          class="mt-10"
          label="Player Name"
          :items="selectionStore.players"
          item-title="playerName"
          item-value="playerId"
          v-model="selectedPlayer"
        ></v-select>

        <v-row justify="center">
          <StyledButton 
            class="mt-10"
            parameter="Filter"
            icon="mdi-filter"
            :disabled="!selectedSeason || !selectedGame || !selectedPlayer"
            @click="filter"
            />
        </v-row>
      </v-col>

      <v-col cols="auto" class="d-none d-md-flex pa-0 align-center">
        <v-divider
          :thickness="5"
          color="var(--theme-primary)"
          vertical
          class="my-1 border-opacity-100"
          style="height: 100%;"
        ></v-divider>
      </v-col>

      <v-row justify="center">
         <v-col cols="12" sm="9" md="10" class="pa-4">
          <template v-if="statisticsStore.ofGame && statisticsStore.ofSeason">
            <div class="text-right mt-8 mb-2">
             <v-btn
               fab
               dark
               color="var(--theme-secondary)"
               @click="refresh" 
             >
               <v-icon dark>mdi-refresh</v-icon>
             </v-btn>
            </div>
            <v-card class="mb-3" variant="outlined" style="width: 100%">
              <v-card-text class="text-center">
                <h2 class="text-h5">Season Stats</h2>
              </v-card-text>

              <v-row no-gutters class="align-center">
                <v-col v-for="(stat, index) in seasonStats" :key="index" class="pa-2">
                  <StatBox 
                    :label="stat.label" 
                    :value="stat.value" 
                    boxWidth="100%"
                  />
                </v-col>
              </v-row>
            </v-card>

            <v-card class="mb-3 mt-8" variant="outlined" style="width: 100%">
              <v-card-text class="text-center">
                <h2 class="text-h5">Game Stats</h2>
              </v-card-text>

             <v-row no-gutters class="align-center">
                <template v-for="(stat, index) in gameStats.filter(s => s.label !== 'Total Points')" :key="'game-'+index">
                  <v-col cols="4" sm="4" md="3" class="pa-2">
                    <StatBox :label="stat.label" :value="stat.value" boxWidth="100%" />
                  </v-col>
                </template>
                <v-col cols="4" sm="4" md="12" class="pa-2">
                  <StatBox 
                    :label="$vuetify.display.mobile ? 'TP' : 'Total Points'" 
                    :value="gameStats.find(s => s.label === 'Total Points')?.value || 0" 
                    boxWidth="100%"
                    position="center"
                  />
                </v-col>
              </v-row>
            </v-card>
          </template>
          <v-alert
            v-else
            type="info"
            variant="tonal"
            class="ma-4 text-center"
          >
            Select a season, game, and player to view statistics
          </v-alert>
        </v-col>
      </v-row>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

const selectionStore = useSelectionStore()
const statisticsStore = useStatisticsStore()

const selectedSeason = ref<string | null>(null)
const selectedGame = ref<string | null>(null)
const selectedPlayer = ref<string | null>(null)

const seasonStats = computed(() => [
  { label: 'PPG', value: statisticsStore.ofSeason?.ppg?.toFixed(1) || '' },
  { label: 'APG', value: statisticsStore.ofSeason?.apg?.toFixed(1) || '' },
  { label: 'RPG', value: statisticsStore.ofSeason?.rpg?.toFixed(1) || '' },
  { label: 'BPG', value: statisticsStore.ofSeason?.bpg?.toFixed(1) || '' },
  { label: 'FT%', value: statisticsStore.ofSeason?.ftConversion?.toFixed(1) || '--' },
  { label: 'Total Points', value: statisticsStore.ofSeason?.totalPoints || '' }
])

const gameStats = computed(() => {
  const stats = statisticsStore.ofGame || []
  
  const ftHit = stats.find(t => t.type === 'FreeThrowHit')?.count ?? 0
  const ftTotal = stats.filter(t => t.type === 'FreeThrowMiss' || t.type === 'FreeThrowHit')
                      .reduce((sum, t) => sum + t.count, 0) ?? 0
                      
  const twoHit = stats.find(t => t.type === 'TwoPointerHit')?.count ?? 0
  const twoTotal = stats.filter(t => t.type === 'TwoPointerMiss' || t.type === 'TwoPointerHit')
                       .reduce((sum, t) => sum + t.count, 0) ?? 0
                       
  const threeHit = stats.find(t => t.type === 'ThreePointerHit')?.count ?? 0
  const threeTotal = stats.filter(t => t.type === 'ThreePointerMiss' || t.type === 'ThreePointerHit')
                         .reduce((sum, t) => sum + t.count, 0) ?? 0
                         
  const totalPoints = stats.reduce((total, t) => t.points ? total + t.points : total, 0) ?? 0

  return [
    { label: 'FT', value: `${ftHit}-${ftTotal}` },
    { label: '2PT', value: `${twoHit}-${twoTotal}` },
    { label: '3PT', value: `${threeHit}-${threeTotal}` },
    { label: 'Assist', value: stats.find(t => t.type === "Assist")?.count ?? 0 },
    { label: 'Rebound', value: stats.find(t => t.type === "Rebound")?.count ?? 0 },
    { label: 'Turnover', value: stats.find(t => t.type === "Turnover")?.count ?? 0 },
    { label: 'Block', value: stats.find(t => t.type === "Block")?.count ?? 0 },
    { label: 'Foul', value: stats.find(t => t.type === "Foul")?.count ?? 0 },
    { 
      label: 'Total Points', 
      value: totalPoints,
      isWide: true
    }
  ]
})

function onSeasonSelect(seasonId: string) {
  selectionStore.fetchSelectionGames(seasonId)
  selectedGame.value = null
  selectedPlayer.value = null
}

function onGameSelect(gameId: string) {
  selectionStore.fetchPlayers(gameId)
  selectedPlayer.value = null
}

function filter() {
  if (selectedSeason.value && selectedGame.value && selectedPlayer.value) {
    statisticsStore.fetchStatistics({
      seasonId: selectedSeason.value,
      gameId: selectedGame.value,
      playerId: selectedPlayer.value
    })
  }
}

function gameTitle(game: any): string {
  return `${game.homeTeamId} vs ${game.visitorTeamId}`
}

function refresh() {
  filter()
}
</script>

<style scoped>
@media (max-width: 1279px) {
  .main-container {
    overflow-y: auto;
    overflow-x: hidden !important;
  }
}

.v-menu__content {
  position: absolute !important;
  max-height: 400px !important;
  overflow-y: auto !important;
  overflow-x: hidden !important;
}
</style>
